apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: nginx-demo-v1
  labels:
    app: nginx-demo-v1
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: nginx-demo-v1
  template:
    metadata:
      labels:
        app: nginx-demo-v1
    spec:
      containers:
      - name: nginx-demo-v1
        image: weihoop/nginx:demo-v1 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 24
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-v1
  labels:
    app: nginx-demo-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-demo-v1
